### ISSUE TITLE
Récupération par liste des statuts de colis

### ISSUE THREAD

**Issue by jebab** [adriens/colisnc-sdk#19]
Le but est de limiter le nombre de requêtes au serveur.

**Comment by adriens** [comment]
Tu peux me dropper un pseudo code de ceui qui est attendu ?

Attention, en backoffice, tu dois me donner les num de colis, je ne me souviens de rien.

**Comment by jebab** [comment]
Requête : get /colis/?ids={id1, id2} 
Réponse : 
[ { "id": "id1", "lastEventId" = "6545" } // colis d'id1 avec son dernier élément
, { "id": "id2", "lastEventId" = "6511" } // colis d'id2 avec son dernier élément
]

**Comment by adriens** [comment]
Parfait, je vois, merci, je vais m'occupper de ça 👍

**Comment by adriens** [comment]
C bon, ça marche, côté SDK c'est très facile à utiliser:

```java
System.out.println("############################################");
List<String> aListOfColis = Arrays.asList(new String[]{"RP733152095CN", "CA107308006SI", "7A53946342222"});
List<ColisDataRow> latestStatus = ColisCrawler.getLatestStatusForColisList(aListOfColis);
Iterator<ColisDataRow> iterLatest = latestStatus.iterator();
ColisDataRow aRow;
while(iterLatest.hasNext()){
    aRow = iterLatest.next();
    System.out.println(aRow);
}
````

**Comment by adriens** [comment]
Si on upagrade l'API, on retrouvre l'id du colis:

![image](https://user-images.githubusercontent.com/5235127/69526676-db8ee780-0fbe-11ea-95fa-fb5a4fdfce91.png)

**Comment by adriens** [comment]
Ok pour toi @jebab ❔ 
Si 👍 pour toi, tu peux fermer ?
