### ISSUE TITLE
Url localisation DUMBEA MAIRIE

### ISSUE THREAD

**Issue by HakumenNC** [adriens/colisnc-sdk#20]
Bonjour,

Pour la localisation `DUMBEA MAIRIE`, l'url doit correspondre à : https://goo.gl/maps/NE1j4MyLNQBZAVwXA

Merci

**Comment by adriens** [comment]
👍

**Comment by adriens** [comment]
Tu peux tester ?

**Comment by adriens** [comment]
Tu peux tester ?

**Comment by adriens** [comment]
Tu peux tester ?

**Comment by HakumenNC** [comment]
C'est bon, Validé ✔️

**Comment by adriens** [comment]
Cool, merci 👍
